---
title: "README"
author: "Elizabeth Davenport"
date: "2025-01-31"
output: word_document
---

# Davenport et al. study on how resource quantity affects infections and impacts of a parasite on hosts
---

The files include all the data and code used to analyze data and create the figures in the Davenport et al. manuscript. Data collection was led by Elizabeth Davenport and supported by Marcin Dziuba, Fiona Corcoran, Natalia Ferreira dos Santos, Kira J. Monell, Paige McCreadie, Siobhan Calhoun, Taleah Nelson, Logan Jacobson, and Riley Manuel. Figures were created by Elizabeth Davenport and Meghan Duffy of the University of Michigan. 

## Description of the data and file structure

There are three main folders in the zip file:
1. scripts: this contains the code used to create figures.

2. data: this contains the data collected during the study.

3. figures: this is the folder where plots will be saved from the output of the R markdown files.

# Parasite Infection and Impacts Data
Data and code for 2024 study led by Elizabeth Davenport

Citation: Resource quantity affects infection success and impacts of a microsporidian on hosts

Authors: Elizabeth S. Davenport 1*, Marcin K. Dziuba 1, Fiona Corcoran 1, Natalia Ferreira dos Santos 1, Kira J. Monell 1, Paige McCreadie 1, Siobhan K. Calhoun 1, Taleah Nelson 1, Logan Jacobson 1, Riley Manuel 1, and Meghan Duffy
        1 Department of Ecology & Evolutionary Biology, University of Michigan, Ann Arbor, MI 48109, USA

Contact: * Author responsible for writing code related to analyses and figures: davenpe@umich.edu
         
Date: January 2025

_______________________________________________________________________________________________________________

DATA

InfectionStatusAndBurden.csv: this data file contains the infection status and spore burden of Daphnia dentifera exposed to a microsporidian parasite. ID = the identification code for experimental individual. Food_Level = resource quantity treatment. Concentration = number of copies per microliter of a microsporidian infecting a host. InfectionStatus = binary response indicating infected (1) or uninfected (0)

Feeding_Rate_Survivorship.csv: this data file contains the survivorship data for the feeding rate experiment. ID = the identification code for experimental individual. Treatment = unexposed or exposed to parasite spores for the experiment. Food.Level = resource quantity for the experiment. Lifespan = day the host died. Status = binary indicator describing whether the host survived to the end of the assay (0) or died earlier (1)

FeedingRates.csv: this data file contains the feeding rate data. Plate = plate identification for each sampling date. Date = date of the assay. Days.PostExposure = number of days after the parasite exposure. Sample.Round = temporal sampling round. Sample = the identification code for experimental individual. Treatment = unexposed (control) or exposed to parasite spores for the experiment. Food = resource quantity for the experiment. Average = raw fluorescence value. Feeding.Rate = calculation of feeding rate of an individual. Binary.Infection.Status = binary response indicating infected (1) or uninfected (0). Infection.Status = status of host indicating no exposure, exposed and infection, or exposed and uninfected.

Ordospora_AE.csv: this data file contains the assimilation efficiency data. ID = individual sample code. Treatment = unexposed or exposed to parasite spores for the experiment. Replicate = replicate number. AE = assimilation efficiency (%).

DOC_Ordospora.csv: this data file contains the dissolved organic carbon release data. Treatment = unexposed or exposed to parasite spores for the experiment. Replicate = replicate number. TOC = total organic carbon released over four hours.

BodyLength.cvs: Individual = individual sample code. Treatment = unexposed (control) or exposed to parasite spores for the experiment. Food.Level = resource quantity for the experiment. Date = date of the assay. Day = number of days after the parasite exposure. Body.Length = body length of individual.
