---
title: "BodyLength"
author: "Elizabeth Davenport"
date: "2025-01-16"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##loading packages
```{r,message=F,warning=F}
library(here)
library(rstatix)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(ggpubr)
library(scales)
library(car)
library(lmtest)
library(AER)
```

## loading files
```{r,message=F,warning=F}
# Tell R where files are stored
here::i_am("scripts/BodyLengthAllRounds.Rmd")

# Load Files
a <- readr::read_csv(here("data/BodyLength.csv"))

```

##making data frames and running statistical tests
```{r,message=F,warning=F}
a <- data.frame(a)

##rename treatments
a$Treatment <- str_replace(a$Treatment, "Control", "Unexposed")
a$Treatment <- str_replace(a$Treatment, "MicG", "Ordospora")

##create a data frame with only high food
only.high = a %>%
  filter(Food.Level =="High")

df.high <- data.frame(only.high)
df.high$Day <- as.numeric(df.high$Day)
df.high$Treatment <- as.factor(df.high$Treatment)
df.high$Body.Length <- as.numeric(df.high$Body.Length)

res.aov2 <- aov(Body.Length ~ Treatment * Day, data = df.high)
summary(res.aov2)
##significant interaction effect of exposure and day

##comparison for specific days
##### Day 24
only.high.d24 = df.high %>%
  filter(Day =="24")

only.high.d24 <- data.frame(only.high.d24)
only.high.d24$Treatment <- as.factor(only.high.d24$Treatment)
only.high.d24$Body.Length <- as.numeric(only.high.d24$Body.Length)
res.hd24 <- wilcox.test(Body.Length ~ Treatment, data = only.high.d24,
                   exact = FALSE)
res.hd24
## significantly different

##create a data frame with only medium food
df.medium = a %>%
  filter(Food.Level =="Medium")
df.medium <- data.frame(df.medium)

df.medium$Day <- as.numeric(df.medium$Day)
df.medium$Treatment <- as.factor(df.medium$Treatment)
df.medium$Body.Length <- as.numeric(df.medium$Body.Length)

medium.res.aov2 <- aov(Body.Length ~ Treatment * Day, data = df.medium)
summary(medium.res.aov2)
##significant effect of treatment and day but no interaction

##create a data frame with only low food
df.low = a %>%
  filter(Food.Level =="Low")

df.low <- data.frame(df.low)
df.low$Day <- as.numeric(df.low$Day)
df.low$Treatment <- as.factor(df.low$Treatment)
df.low$Body.Length <- as.numeric(df.low$Body.Length)

low.res.aov2 <- aov(Body.Length ~ Treatment * Day, data = df.low)
summary(low.res.aov2)
## Significant interaction between exposure and day

##comparison for specific days
##### Day 24
only.low.d3 = df.low %>%
  filter(Day =="3")

only.low.d3 <- data.frame(only.low.d3)
only.low.d3$Treatment <- as.factor(only.low.d3$Treatment)
only.low.d3$Body.Length <- as.numeric(only.low.d3$Body.Length)
res.ld3 <- wilcox.test(Body.Length ~ Treatment, data = only.low.d3,
                   exact = FALSE)
res.ld3
## significantly different
```



```{r,message=F,warning=F}
##color scheme for plots
cols <- c("Unexposed"= "#0072B2",
          "Ordospora"= "yellow3")

##high food plot
high.body <- ggplot(data=df.high,aes(x=Day,y=Body.Length,color=as.factor(Treatment), 
                                     fill = as.factor(Treatment))) +
  geom_smooth(span=.9)+
  geom_point(size = .75,shape = 21, position = position_jitterdodge(jitter.width = 0))+
  scale_y_continuous(limits = c(600,1900), breaks = seq(600,1900,200))+
  scale_x_continuous(limits = c(1,26), breaks = seq(3,24,7))+
  scale_color_manual(values = cols)+
  scale_fill_manual(values = cols)+
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"))+
  ggtitle("High Food (100%)") +
  labs(x = (""), y=(""), color = ("Treatment"))+
  theme(plot.title = element_text(face = "bold",size = 10),
        axis.text=element_text(size=8, face = "bold"), 
        axis.title=element_text(size=10,face="bold"),
        legend.position = "bottom")+ guides(fill = "none", color=guide_legend(override.aes=list(fill=NA)))

high.body
```


##Medium Food
```{r,message=F,warning=F}
medium.body <- ggplot(data=df.medium,aes(x=Day,y=Body.Length, color = as.factor(Treatment), fill=as.factor(Treatment))) +
  geom_smooth(span=.9)+
  geom_point(size = .75, shape = 21, position = position_jitterdodge(jitter.width = 0))+
  scale_y_continuous(limits = c(600,1900), breaks = seq(600,1900,200))+
  scale_x_continuous(limits = c(1,26), breaks = seq(3,24,7))+
  scale_fill_manual(values = cols)+
  scale_color_manual(values = cols)+
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"))+
  ggtitle("Medium Food (12.5%)") +
  labs(x = ("Days Post-exposure"), y=(""), color = ("Treatment"))+
  theme(plot.title = element_text(face = "bold",size = 10),
        axis.text=element_text(size=8, face = "bold"), 
        axis.title=element_text(size=10,face="bold"),
        legend.position = "bottom") + guides(fill = "none", color=guide_legend(override.aes=list(fill=NA)))

medium.body
```


## Low Food
```{r,message=F,warning=F}
low.body <- ggplot(data=df.low,aes(x=Day,y=Body.Length,color = as.factor(Treatment), 
                                 fill=as.factor(Treatment))) +
  geom_smooth(span=.9)+
  geom_point(size = .75,shape = 21, position = position_jitterdodge(jitter.width = 0))+
  scale_y_continuous(limits = c(600,1900), breaks = seq(600,1900,200))+
  scale_x_continuous(limits = c(1,26), breaks = seq(3,24,7))+
  scale_fill_manual(values = cols)+
  scale_color_manual(values = cols)+
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"))+
  ggtitle("Low Food (6.25%)") +
  labs(x = (""), y=("Body Length (um)"), color = ("Treatment"))+
  theme(plot.title = element_text(face = "bold",size = 10),
        axis.text=element_text(size=8, face = "bold"), 
        axis.title=element_text(size=10,face="bold"),
        legend.position = "bottom") + guides(fill = "none", color=guide_legend(override.aes=list(fill=NA)))

low.body
```


### combo
```{r,message=F,warning=F}
combined = ggarrange(low.body,medium.body, high.body, 
                     nrow = 1, ncol = 3,
                     common.legend = TRUE,
                     legend="bottom")


#### saving combined plot
ggsave(here("figures", "BodyLengthComboPlot.jpg"), combined, width = 8, height = 4, dpi = 600)
```




